name: polymer_elements_examples
version: 0.1.0
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: Polymer polymer-elements for Dart examples.
homepage: https://www.dartlang.org/polymer/
dependencies:
  browser: any
  polymer: ^1.0.0
  polymer_elements:
    path: ..
  polymer_interop: ^0.2.0
  reflectable: ^0.2.1
  web_components: ^0.12.0
dev_dependencies:
  github: '>=2.2.3+1 <3.0.0'
  path: '>=1.3.6 <2.0.0'
  test: ^0.12.0
  yaml: ">=1.0.0 <3.0.0"
  quiver: '>=0.21.4 <0.22.0'
  crypto: '>=0.9.1 <0.10.0'
dependency_overrides:
  polymer:
    git:
      url: git@github.com:dart-lang/polymer-dart.git
      ref: aea190df60e6c9d20078d89919443dea8e1b1997
  reflectable: 0.2.1
  polymer_interop:
    git:
      ref: 0.2.0-dev
      url: https://github.com/dart-lang/polymer_interop.git
environment:
  sdk: '>=1.6.0 <2.0.0'
transformers:
- web_components:
#    $include: test/*_test.html
    entry_points: [
      "web/index.html",

      "web/seed-element/index.html",
      "web/paper-styles/index.html",
      "web/iron-meta/index.html",
      "web/paper-item/index.html",
      "web/iron-doc-viewer/index.html",
      "web/iron-list/index.html",
      "web/neon-elements/index.html",
      "web/molecules/index.html",
      "web/gold-elements/index.html",
      "web/iron-elements/index.html",
      "web/prism-element/index.html",
      "web/paper-menu/index.html",
      "web/platinum-elements/index.html",
      "web/paper-radio-button/index.html",
      "web/paper-checkbox/index.html",
      "web/paper-toggle-button/index.html",
      "web/test-fixture/index.html",
      "web/iron-iconset-svg/index.html",
      "web/iron-iconset/index.html",
      "web/iron-icon/index.html",
      "web/iron-icons/index.html",
      "web/iron-ajax/index.html",
      "web/iron-image/index.html",
      "web/marked-element/index.html",
      "web/iron-collapse/index.html",
      "web/paper-header-panel/index.html",
      "web/iron-selector/index.html",
      "web/style-guide/index.html",
      "web/paper-drawer-panel/index.html",
      "web/iron-media-query/index.html",
      "web/quick-element/index.html",
      "web/paper-material/index.html",
      "web/polymer-starter-kit/index.html",
      "web/platinum-push-messaging/index.html",
      "web/paper-ripple/index.html",
      "web/paper-toolbar/index.html",
      "web/iron-behaviors/index.html",
      "web/iron-flex-layout/index.html",
      "web/paper-behaviors/index.html",
      "web/platinum-sw/index.html",
      "web/paper-radio-group/index.html",
      "web/iron-component-page/index.html",
      "web/paper-input/index.html",
      "web/iron-input/index.html",
      "web/paper-elements/index.html",
      "web/iron-test-helpers/index.html",
      "web/paper-spinner/index.html",
      "web/paper-button/index.html",
      "web/iron-range-behavior/index.html",
      "web/iron-autogrow-textarea/index.html",
      "web/iron-menu-behavior/index.html",
      "web/paper-fab/index.html",
      "web/iron-fit-behavior/index.html",
      "web/paper-progress/index.html",
      "web/paper-slider/index.html",
      "web/iron-signals/index.html",
      "web/iron-localstorage/index.html",
      "web/paper-icon-button/index.html",
      "web/iron-resizable-behavior/index.html",
      "web/iron-jsonp-library/index.html",
      "web/iron-overlay-behavior/index.html",
      "web/iron-pages/index.html",
      "web/paper-dialog-behavior/index.html",
      "web/paper-dialog-scrollable/index.html",
      "web/paper-toast/index.html",
      "web/paper-tabs/index.html",
      "web/chartjs-element/index.html",
      "web/gold-cc-cvc-input/index.html",
      "web/gold-cc-expiration-input/index.html",
      "web/paper-menu-button/index.html",
      "web/gold-cc-input/index.html",
      "web/iron-a11y-keys-behavior/index.html",
      "web/iron-validatable-behavior/index.html",
      "web/iron-validator-behavior/index.html",
      "web/gold-email-input/index.html",
      "web/gold-phone-input/index.html",
      "web/gold-zip-input/index.html",
      "web/app-layout-templates/index.html",
      "web/neon-animation/index.html",
      "web/iron-form-element-behavior/index.html",
      "web/iron-form/index.html",
      "web/paper-dialog/index.html",
      "web/iron-a11y-keys/index.html",
      "web/paper-scroll-header-panel/index.html",
      "web/iron-a11y-announcer/index.html",
      "web/iron-dropdown/index.html",
      "web/font-roboto/index.html",
      "web/paper-tooltip/index.html",
      "web/iron-checked-element-behavior/index.html",
      "web/font-roboto-local/index.html",
      "web/paper-badge/index.html",
      "web/paper-dropdown-menu/index.html",
      "web/paper-card/index.html",
      "web/platinum-bluetooth/index.html",
      "web/platinum-https-redirect/index.html",
      "web/test-all/index.html",
      "web/iron-label/index.html",
      "web/google-map/index.html",
      "web/google-signin/index.html",
      "web/google-streetview-pano/index.html",
      "web/google-apis/index.html",
      "web/google-hangout-button/index.html",
      "web/google-calendar/index.html",
      "web/google-chart/index.html",
      "web/google-sheets/index.html",
      "web/google-youtube/index.html",
      "web/google-drive/index.html",
      "web/google-youtube-upload/index.html",
      "web/google-url-shortener/index.html",
      "web/googlewebcomponents.github.io/index.html",
      "web/google-cloud/index.html",
      "web/google-analytics/index.html",
      "web/demos/index.html",
      "web/style-guide/index.html",
      "web/google-castable-video/index.html",
      "web/google-youtube-video-wall/index.html",
      "web/google-recaptcha/index.html",
      "web/firebase-element/index.html",
      "web/google-web-components/index.html",
      "web/google-feeds/index.html",
      "web/google-domain-user-picker/index.html"]

- reflectable:
    entry_points: [
      "web/index.dart",

      "web/seed-element/index.dart",
      "web/paper-styles/index.dart",
      "web/iron-meta/index.dart",
      "web/paper-item/index.dart",
      "web/iron-doc-viewer/index.dart",
      "web/iron-list/index.dart",
      "web/neon-elements/index.dart",
      "web/molecules/index.dart",
      "web/gold-elements/index.dart",
      "web/iron-elements/index.dart",
      "web/prism-element/index.dart",
      "web/paper-menu/index.dart",
      "web/platinum-elements/index.dart",
      "web/paper-radio-button/index.dart",
      "web/paper-checkbox/index.dart",
      "web/paper-toggle-button/index.dart",
      "web/test-fixture/index.dart",
      "web/iron-iconset-svg/index.dart",
      "web/iron-iconset/index.dart",
      "web/iron-icon/index.dart",
      "web/iron-icons/index.dart",
      "web/iron-ajax/index.dart",
      "web/iron-image/index.dart",
      "web/marked-element/index.dart",
      "web/iron-collapse/index.dart",
      "web/paper-header-panel/index.dart",
      "web/iron-selector/index.dart",
      "web/style-guide/index.dart",
      "web/paper-drawer-panel/index.dart",
      "web/iron-media-query/index.dart",
      "web/quick-element/index.dart",
      "web/paper-material/index.dart",
      "web/polymer-starter-kit/index.dart",
      "web/platinum-push-messaging/index.dart",
      "web/paper-ripple/index.dart",
      "web/paper-toolbar/index.dart",
      "web/iron-behaviors/index.dart",
      "web/iron-flex-layout/index.dart",
      "web/paper-behaviors/index.dart",
      "web/platinum-sw/index.dart",
      "web/paper-radio-group/index.dart",
      "web/iron-component-page/index.dart",
      "web/paper-input/index.dart",
      "web/iron-input/index.dart",
      "web/paper-elements/index.dart",
      "web/iron-test-helpers/index.dart",
      "web/paper-spinner/index.dart",
      "web/paper-button/index.dart",
      "web/iron-range-behavior/index.dart",
      "web/iron-autogrow-textarea/index.dart",
      "web/iron-menu-behavior/index.dart",
      "web/paper-fab/index.dart",
      "web/iron-fit-behavior/index.dart",
      "web/paper-progress/index.dart",
      "web/paper-slider/index.dart",
      "web/iron-signals/index.dart",
      "web/iron-localstorage/index.dart",
      "web/paper-icon-button/index.dart",
      "web/iron-resizable-behavior/index.dart",
      "web/iron-jsonp-library/index.dart",
      "web/iron-overlay-behavior/index.dart",
      "web/iron-pages/index.dart",
      "web/paper-dialog-behavior/index.dart",
      "web/paper-dialog-scrollable/index.dart",
      "web/paper-toast/index.dart",
      "web/paper-tabs/index.dart",
      "web/chartjs-element/index.dart",
      "web/gold-cc-cvc-input/index.dart",
      "web/gold-cc-expiration-input/index.dart",
      "web/paper-menu-button/index.dart",
      "web/gold-cc-input/index.dart",
      "web/iron-a11y-keys-behavior/index.dart",
      "web/iron-validatable-behavior/index.dart",
      "web/iron-validator-behavior/index.dart",
      "web/gold-email-input/index.dart",
      "web/gold-phone-input/index.dart",
      "web/gold-zip-input/index.dart",
      "web/app-layout-templates/index.dart",
      "web/neon-animation/index.dart",
      "web/iron-form-element-behavior/index.dart",
      "web/iron-form/index.dart",
      "web/paper-dialog/index.dart",
      "web/iron-a11y-keys/index.dart",
      "web/paper-scroll-header-panel/index.dart",
      "web/iron-a11y-announcer/index.dart",
      "web/iron-dropdown/index.dart",
      "web/font-roboto/index.dart",
      "web/paper-tooltip/index.dart",
      "web/iron-checked-element-behavior/index.dart",
      "web/font-roboto-local/index.dart",
      "web/paper-badge/index.dart",
      "web/paper-dropdown-menu/index.dart",
      "web/paper-card/index.dart",
      "web/platinum-bluetooth/index.dart",
      "web/platinum-https-redirect/index.dart",
      "web/test-all/index.dart",
      "web/iron-label/index.dart",
      "web/google-map/index.dart",
      "web/google-signin/index.dart",
      "web/google-streetview-pano/index.dart",
      "web/google-apis/index.dart",
      "web/google-hangout-button/index.dart",
      "web/google-calendar/index.dart",
      "web/google-chart/index.dart",
      "web/google-sheets/index.dart",
      "web/google-youtube/index.dart",
      "web/google-drive/index.dart",
      "web/google-youtube-upload/index.dart",
      "web/google-url-shortener/index.dart",
      "web/googlewebcomponents.github.io/index.dart",
      "web/google-cloud/index.dart",
      "web/google-analytics/index.dart",
      "web/demos/index.dart",
      "web/style-guide/index.dart",
      "web/google-castable-video/index.dart",
      "web/google-youtube-video-wall/index.dart",
      "web/google-recaptcha/index.dart",
      "web/firebase-element/index.dart",
      "web/google-web-components/index.dart",
      "web/google-feeds/index.dart",
      "web/google-domain-user-picker/index.dart"
    ]
- test/pub_serve:
    $include: test/**_test{.*,}.dart
- $dart2js:
    minify: true
    $include: '**/*.bootstrap.initialize.dart'
