name: polymer_elements_demo
version: 0.1.0
author: Polymer.dart Authors <web-ui-dev@dartlang.org>
description: Polymer polymer-elements for Dart examples.
homepage: https://www.dartlang.org/polymer/
dependencies:
  browser: any
  polymer:
    git:
      url: git@github.com:dart-lang/polymer-dart.git
      ref: behaviors
  polymer_elements:
    path: ..
  polymer_interop: ^0.2.0
  reflectable: ^0.2.1
  web_components: ^0.12.0
dev_dependencies:
  github: '>=2.2.3+1 <3.0.0'
  path: '>=1.3.6 <2.0.0'
  test: ^0.12.0
  yaml: ">=1.0.0 <3.0.0"
  quiver: '>=0.21.4 <0.22.0'
  crypto: '>=0.9.1 <0.10.0'
dependency_overrides:
  reflectable: 0.2.1
  polymer_interop:
    git:
      ref: 0.2.0-dev
      url: https://github.com/dart-lang/polymer_interop.git
environment:
  sdk: '>=1.6.0 <2.0.0'
transformers:
- web_components:
    entry_points:
    - web/firebase_element/index.html
    - web/gold_cc_cvc_input/index.html
    - web/gold_cc_expiration_input/index.html
    - web/gold_cc_input/index.html
- reflectable:
    entry_points:
    - web/firebase_element/index.dart
    - web/gold_cc_cvc_input/index.dart
    - web/gold_cc_expiration_input/index.dart
    - web/gold_cc_input/index.dart
- test/pub_serve:
    $include: test/**_test{.*,}.dart
- $dart2js:
    minify: true
    $include: '**/*.bootstrap.initialize.dart'
